sfhnat-y += sf_hnat.o
sfhnat-y += sf_hnat_debug.o
sfhnat-$(CONFIG_SFAX8_HNAT_TEST_TOOL) += sf_pcap_parse.o
sfhnat-$(CONFIG_SFAX8_HNAT_TEST_TOOL) += sf_test_thread_poll.o
obj-$(CONFIG_SFAX8_HNAT_DRIVER) += sfhnat.o
