include $(TOPDIR)/rules.mk

LUCI2_TITLE:=send mail as feedback
LUCI2_DEPENDS:=+luci2-siflower +busybox +@BUSYBOX_CUSTOM +@BUSYBOX_CONFIG_SENDMAIL
LUCI2_DESCRIPTION:=send mail as feedback

include ../../luci2.mk

# call BuildPackage - OpenWrt buildroot signature
