include $(TOPDIR)/rules.mk

LUCI2_TITLE:=wan-lan port adaptive
LUCI2_DEPENDS:=+luci2-siflower +port_adaptive
LUCI2_DESCRIPTION:=wan-lan port adaptive

include ../../luci2.mk

# call BuildPackage - OpenWrt buildroot signature
